conventional-commits:
  - type: 'fix'
    nouns: ['fix', 'fixed', 'FIX', 'FIXED']
    labels: ['bug']
  - type: 'feature'
    nouns: ['feat', 'feature', 'FEAT', 'FEATURE']
    labels: ['enhancement']
  - type: 'breaking_change'
    nouns: ['BREAKING CHANGE']
    labels: ['BREAKING CHANGE']
