%YAML 1.2
---
conventional-commits:
  - fix:
      commit: ['fix', 'fixed']
      labels: ['bug']
  - feature:
      commit: ['feat', 'feature']
      labels: ['enhacement']
  - breaking_change:
      commit: ['breaking change']
      labels: ['BREAKING CHANGE']
  - documentation:
      commit: ['doc', 'docs', 'docu', 'documentation']
      labels: ['documentation']
