name: 'Assign Labels From Conventional Commits'
description: 'Assign labels to pull-request parsing conventional commits standard'
inputs:
  pull-request-number:
    description: 'The pull request'' number where labels will be assigned'
    required: true
  github-token:
    description: 'The Github token.'
    required: true
  clear-all-labels-to-start:
    description: 'Should be removed all labels assigned to the pull request before begin.'
    required: false
    default: 'false'
  remove-labels-not-found:
    description: 'Should be removed the labels previously assigned that don''t present a reference in the current conventional commits.'
    required: false
    default: 'true'
  conventional-commits:
    description: 'String with the YAML object or path to file YAML that contains a list with conventional commits and the labels matching that must be assigned'
    required: false
    default: 'conventional-commits.yml'
  not-apply-changes:
    description: 'Should will executing the action without applying any change to the repository'
    required: false
    default: 'false'
outputs:
  labels-previous:
    description: 'List of the labels assigned before updating them'
  labels-assigned:
    description: 'List of the labels added after updating them'
  labels-removed:
    description: 'List of the labels removed after updating them'
  labels-current:
    description: 'List of the labels assigned after updating them'
  action-status:
    description: 'Execution status of the action'
  action-message:
    description: 'Message associated to the current status of the action'
runs:
  using: 'node16'
  main: 'dist/index.js'
