name: Tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test assign labels action
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Execute assign labels test
        id: action-assign-labels
        uses: ./
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          clear-all-labels-to-start: false
          remove-labels-not-found: true
          conventional-commits-file: './.github/conventional-commits.test.yml'
          not-apply-changes: false

      - name: assert
        run: |
          if [[ "${{ steps.action-assign-labels.outputs.action-status }}" != "ENDED" ]]; then echo "want status ENDED, got ${{ steps.action-assign-labels.outputs.action-status }}"; exit 1; fi
          if [[ "${{ steps.action-assign-labels.outputs.action-message }}" != "" ]]; then echo "want message empty, got ${{ steps.action-assign-labels.outputs.action-message }}"; exit 1; fi

          if [[ "${{ steps.action-assign-labels.outputs.labels-assigned }}" != "" ]]; then echo "want labels-assigned empty, got ${{ steps.action-assign-labels.outputs.labels-assigned }}"; exit 1; fi
          if [[ "${{ steps.action-assign-labels.outputs.labels-removed }}" != "" ]]; then echo "want labels-removed empty, got ${{ steps.action-assign-labels.outputs.labels-removed }}"; exit 1; fi
